module.exports = {
  darkMode: 'class',
  content: [
    './public/index.html',
    './public/js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e6e8ea',
        'surface-bright': '#f7f9fb',
        'on-primary-fixed': '#00174b',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed-variant': '#003ea8',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary-fixed-variant': '#3f465c',
        'tertiary-container': '#656d84',
        'on-primary-container': '#eeefff',
        'on-surface': '#191c1e',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-tint': '#0053db',
        'primary-container': '#2563eb',
        'inverse-primary': '#b4c5ff',
        'secondary-fixed': '#d3e4fe',
        'on-surface-variant': '#434655',
        'secondary-fixed-dim': '#b7c8e1',
        'outline-variant': '#c3c6d7',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#131b2e',
        'surface-dim': '#d8dadc',
        'on-secondary-container': '#54647a',
        surface: '#f7f9fb',
        'on-background': '#191c1e',
        'inverse-surface': '#2d3133',
        'on-primary': '#ffffff',
        tertiary: '#4d556b',
        primary: '#004ac6',
        'tertiary-fixed': '#dae2fd',
        'on-error-container': '#93000a',
        'surface-variant': '#e0e3e5',
        'surface-container-low': '#f2f4f6',
        'surface-container-highest': '#e0e3e5',
        'tertiary-fixed-dim': '#bec6e0',
        'primary-fixed': '#dbe1ff',
        'on-tertiary-container': '#eef0ff',
        secondary: '#505f76',
        'on-error': '#ffffff',
        outline: '#737686',
        'on-secondary-fixed-variant': '#38485d',
        'on-tertiary': '#ffffff',
        'secondary-container': '#d0e1fb',
        'surface-container': '#eceef0',
        'on-secondary-fixed': '#0b1c30',
        'error-container': '#ffdad6',
        background: '#f7f9fb',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        'stack-gap': '12px',
        'card-padding': '16px',
        'container-padding': '16px',
        'inline-gap': '8px',
      },
      fontFamily: {
        'label-caps': ['ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        h2: ['ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        'body-md': ['ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        'body-lg': ['ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        'status-chip': ['ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        h1: ['ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        h2: ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'status-chip': ['12px', { lineHeight: '12px', fontWeight: '600' }],
        h1: ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
};
